#!/bin/bash

while IFS=':' read -r username _ userid _ _ home _; do
    # Display the required information
    echo "Username: $username"
    echo "User ID: $userid"
    echo "Home Directory: $home"
done < /etc/passwd

